language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/registrations_test;

node_js:
  - 12

before_script:
  - psql -c 'create database registrations_test;' -U postgres
  - psql -U postgres -d registrations_test -a -f database.sql


services:
  - postgresql;